# Generated by Django 5.1.7 on 2025-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_language_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
