# Generated by Django 5.1.7 on 2025-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_map',
            field=models.CharField(choices=[('google', 'Google Maps'), ('yandex', 'Yandex Maps'), ('2gis', '2GIS')], default='google', max_length=20),
        ),
    ]
