# Generated by Django 5.1.7 on 2025-05-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city',
        ),
    ]
