# Generated by Django 5.1.7 on 2025-05-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_location_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_map',
        ),
    ]
