# Generated by Django 5.1.7 on 2025-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_preferred_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
