# Generated by Django 5.1.7 on 2025-05-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
    ]
