# Generated by Django 5.1.7 on 2025-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
