# Generated by Django 5.1.7 on 2025-04-24 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_options_car_brand_en_car_brand_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], default='automatic', max_length=20),
        ),
    ]
