# Generated by Django 5.1.7 on 2025-04-24 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_condition_car_features_car_fuel_type_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
